-- Editorial catalog corrective migration. Safe for existing rooms and histories:
-- it upserts current cards and moves older active cards to reserve instead of deleting them.
update public.prompts set status='reserve' where status='active';
insert into public.prompts(id,category,intensity,status,text,side_a,side_b) values
('asado-tarde','Asado','tranqui','active','Llegar con hielo a un asado te habilita a caer tarde.','Habilita','No habilita'),
('asado-parrilla','Asado','tranqui','active','El que se adueña de la parrilla no debería recibir sugerencias.','Sin consejos','Se escucha'),
('asado-sobras','Asado','tranqui','active','Llevarse un tupper del asado sin preguntar es de confianza.','Está bien','Se pregunta'),
('asado-pan','Asado','tranqui','active','El pan con chimichurri merece protagonismo propio.','Protagonista','Acompaña'),
('mate-excusa','Mate','tranqui','active','El mate es más excusa para charlar que bebida.','Es excusa','Es bebida'),
('mate-lavado','Mate','tranqui','active','El mate lavado se sigue tomando por respeto, no por gusto.','Por respeto','Se cambia'),
('mate-ronda','Mate','tranqui','active','Devolver el mate sin avisar que está lavado es una traición menor.','Es traición','No tanto'),
('cafe-charla','Mate','tranqui','active','Un café frío se termina igual si la charla está buena.','Se termina','Se cambia'),
('previa-boliche','Salidas','tranqui','active','Una previa que se pone buena puede justificar no ir al boliche.','De una','Se sale igual'),
('menu-antes','Salidas','tranqui','active','Mirar el menú antes de llegar evita discusiones inútiles.','Evita bardo','Le quita gracia'),
('salida-postre','Salidas','tranqui','active','Pedir un postre para compartir y comer más de la mitad es traición.','Es traición','Es normal'),
('fila-bar','Salidas','tranqui','active','Hacer fila para entrar forma parte de la salida.','Es parte','Es un bajón'),
('maneja-musica','Música','tranqui','active','Quien maneja puede elegir la música del viaje.','Puede elegir','Se negocia'),
('playlist-viaje','Música','tranqui','active','Armar la playlist del viaje da demasiado poder.','Demasiado','El justo'),
('musica-prioridad','Música','tranqui','active','El que puso el parlante tiene prioridad, no control total.','Prioridad','Control total'),
('cancion-conocida','Música','tranqui','active','Cantar mal un tema conocido mejora la juntada.','La mejora','La arruina'),
('grupo-nombre','Amistades','tranqui','active','Un grupo de WhatsApp sin nombre raro está incompleto.','Está incompleto','Da igual'),
('plan-sorpresa','Amistades','tranqui','active','Un buen plan sorpresa necesita una persona cómplice.','La necesita','No hace falta'),
('apodo-grupo','Amistades','tranqui','active','Los apodos del grupo no necesitan explicación para funcionar.','No necesitan','Se explican'),
('visita-improvisada','Amistades','tranqui','active','Caer sin avisar puede ser un gesto lindo si hay confianza.','Puede ser lindo','Se avisa'),
('memes','Redes','tranqui','active','Un meme bien mandado responde mejor que un párrafo.','Responde mejor','No reemplaza'),
('redes-borrar','Redes','tranqui','active','Borrar una historia enseguida genera más curiosidad que subirla.','Genera más','Da igual'),
('foto-grupal','Redes','tranqui','active','Una foto grupal vale aunque nadie la suba.','Vale igual','Pierde sentido'),
('visto-amigo','Redes','tranqui','active','Clavar visto a un amigo cercano no necesita disculpas.','No necesita','Se explica'),
('facultad-leer','Facultad','tranqui','active','Ir a clase sin leer puede valer la pena igual.','Vale igual','No alcanza'),
('facultad-grupo','Facultad','tranqui','active','El trabajo grupal sirve para elegir mejor a tus amigos.','Sirve','Es exagerado'),
('apuntes-prolijos','Facultad','tranqui','active','Prestar apuntes prolijos da derecho a pedirlos de vuelta.','Da derecho','Se comparten'),
('parcial-descanso','Facultad','tranqui','active','Descansar antes de un parcial puede rendir más que repasar por pánico.','Rinde más','Se repasa'),
('trabajo-camara','Laburo','tranqui','active','Tener la cámara apagada puede mejorar una reunión.','La mejora','La empeora'),
('laburo-almuerzo','Laburo','tranqui','active','Almorzar frente a la compu no cuenta como descanso.','No cuenta','Sí cuenta'),
('laburo-mate','Laburo','tranqui','active','Llevar mate al trabajo mejora cualquier oficina.','La mejora','Distrae'),
('mensaje-horario','Laburo','tranqui','active','Un mensaje de trabajo fuera de horario puede esperar al día siguiente.','Puede esperar','Se responde'),
('viaje-improvisar','Viajes','tranqui','active','En un viaje, dejar una tarde sin plan es obligatorio.','Es obligatorio','Se organiza'),
('viaje-ventana','Viajes','tranqui','active','El asiento de ventana se pide antes de subir.','Se pide','Se negocia'),
('valija-liviana','Viajes','tranqui','active','Viajar liviano gana aunque falte algo.','Gana','Es arriesgado'),
('mapa-viaje','Viajes','tranqui','active','Perderse un poco mejora el recuerdo del viaje.','Lo mejora','Hace perder tiempo'),
('cocina-lava','Convivencia','tranqui','active','El que cocina se gana el derecho a no lavar ni un plato.','No lava','Lava igual'),
('lavar-platos','Convivencia','tranqui','active','Dejar platos en remojo cuenta como una promesa, no como lavado.','Es promesa','Cuenta igual'),
('heladera-ajena','Convivencia','tranqui','active','Abrir la heladera ajena requiere confianza, no permiso.','Confianza basta','Se pregunta'),
('manta-sillon','Convivencia','tranqui','active','La manta del sillón tiene dueño aunque nadie lo admita.','Tiene dueño','Es de todos'),
('vaquita-redonda','Plata','tranqui','active','La vaquita se redondea para arriba y nadie lleva la cuenta.','Se redondea','Se calcula'),
('transferencia-despues','Plata','tranqui','active','Pagar después por transferencia puede ser igual de responsable.','Es responsable','Se paga ahí'),
('propina-grupo','Plata','tranqui','active','La propina se decide entre todos, no por quien paga.','Entre todos','Decide quien paga'),
('oferta-comun','Plata','tranqui','active','Compartir una promo aunque no convenga tanto une al grupo.','Une al grupo','No tiene sentido'),
('juego-reglas','Juegos','tranqui','active','El que pierde no puede proponer reglas nuevas de inmediato.','No puede','Puede proponer'),
('truco-falta','Juegos','tranqui','active','Cantar falta envido sin cartas también es parte del truco.','Es parte','Es demasiado'),
('juego-tutorial','Juegos','tranqui','active','Saltarse el tutorial es una forma válida de aprender.','Es válida','Es un error'),
('juego-equipo','Juegos','tranqui','active','Elegir equipos por sorteo evita más bardo que elegir por amistad.','Evita bardo','Quita gracia'),
('futbol-relato','Fútbol','tranqui','active','Ver un partido con relato en la radio tiene más clima.','Tiene más clima','No hace falta'),
('futbol-silencio','Fútbol','tranqui','active','Durante un penal importante se respeta el silencio.','Se respeta','Se vive hablando'),
('futbol-asado','Fútbol','tranqui','active','Un partido se disfruta más si hay algo picando al lado.','Se disfruta más','Distrae'),
('futbol-repeticion','Fútbol','tranqui','active','Ver la repetición del gol tres veces es necesario.','Es necesario','Una alcanza'),
('previa-hora','Planes','tranqui','active','La hora de una previa es una referencia, no un contrato.','Referencia','Contrato'),
('plan-domingo','Planes','tranqui','active','Un domingo sin plan puede ser un plan perfecto.','Es perfecto','Se desperdicia'),
('cumple-tema','Planes','tranqui','active','Un cumpleaños con temática mejora aunque nadie se disfrace.','Lo mejora','Es de más'),
('reserva-lugar','Planes','tranqui','active','Reservar mesa para mucha gente obliga a llegar a horario.','Obliga','No tanto'),
('audio-largo','Hábitos','tranqui','active','Un audio de más de dos minutos necesita una buena razón.','La necesita','Es normal'),
('siesta','Hábitos','tranqui','active','Una siesta larga puede salvar un día entero.','Lo salva','Lo desordena'),
('celular-cama','Hábitos','tranqui','active','Mirar el celular en la cama cuenta como seguir despierto.','Cuenta','No cuenta'),
('pizza-fria','Hábitos','tranqui','active','La pizza fría del día siguiente tiene su propio mérito.','Lo tiene','Ni cerca'),
('asado-ensalada','Asado','tranqui','reserve','La ensalada en un asado merece más respeto del que recibe.','Merece respeto','Es relleno'),
('mate-azucar','Mate','tranqui','reserve','Ponerle azúcar al mate se avisa antes de cebar.','Se avisa','Da igual'),
('salida-guardarropa','Salidas','tranqui','reserve','Dejar el abrigo en guardarropa compra tranquilidad.','La compra','Es gasto de más'),
('musica-auriculares','Música','tranqui','reserve','Compartir auriculares es un gesto de confianza.','Lo es','Es incómodo'),
('amistad-ubicacion','Amistades','tranqui','reserve','Mandar ubicación en vivo evita más problemas de los que crea.','Evita más','Crea más'),
('redes-comentario','Redes','tranqui','reserve','Comentar una foto de un amigo da más vergüenza que un like.','Da más','Da menos'),
('facultad-cafe','Facultad','tranqui','reserve','Estudiar con café mejora la concentración aunque sea placebo.','La mejora','Es placebo'),
('viaje-fotos','Viajes','tranqui','reserve','Sacar muchas fotos en viaje ayuda a recordar mejor.','Ayuda','Desconecta'),
('convi-ventana','Convivencia','tranqui','reserve','Dormir con la ventana abierta se negocia cada noche.','Se negocia','Decide quien duerme'),
('plata-regalo','Plata','tranqui','reserve','Un regalo grupal tiene más valor que varios regalos chicos.','Tiene más','Pierde gracia'),
('juego-revancha','Juegos','tranqui','reserve','Pedir revancha enseguida es señal de amor propio.','Lo es','Es capricho'),
('futbol-camiseta','Fútbol','tranqui','reserve','Ver un partido con camiseta cambia la experiencia.','La cambia','Es lo mismo'),
('plan-lluvia','Planes','tranqui','reserve','Un plan con lluvia necesita plan B desde el inicio.','Lo necesita','Se improvisa'),
('habito-desayuno','Hábitos','tranqui','reserve','Desayunar salado le gana al desayuno dulce.','Le gana','Pierde'),
('asado-postre','Asado','tranqui','reserve','Llevar postre al asado cuenta como aporte serio.','Cuenta serio','Es extra'),
('mate-termo','Mate','tranqui','reserve','Compartir termo es tan importante como compartir mate.','Es importante','No tanto'),
('salida-reserva','Salidas','tranqui','reserve','Elegir un bar nuevo es mejor que volver al de siempre.','Mejor probar','Mejor volver'),
('musica-volumen','Música','tranqui','reserve','Bajar la música para hablar no arruina el clima.','No arruina','Lo arruina'),
('amistad-favor','Amistades','tranqui','reserve','Hacer un favor sin contarlo después vale el doble.','Vale doble','Da igual'),
('tecnologia-notas','Hábitos','tranqui','reserve','Anotar todo en el celular libera la cabeza.','La libera','La ocupa'),
('asado-carne','Asado','bardo','active','El que llega con hambre al asado no puede preguntar cada diez minutos por la carne.','No puede','Puede'),
('asado-critico','Asado','bardo','active','Opinar de la parrilla sin acercarse al fuego es caretear.','Es caretear','Es ayudar'),
('asado-hielo','Asado','bardo','active','Quien trae hielo tarde no puede reclamar el primer fernet.','No puede','Puede'),
('asado-vegetariano','Asado','bardo','active','Llevar algo vegetariano no te exime de traer postre.','No exime','Sí exime'),
('mate-ultimo','Mate','bardo','active','El que toma el último mate y no vuelve a cebar se hizo el boludo.','Se hizo','No debe'),
('mate-celular','Mate','bardo','active','Mirar el celular mientras cebás arruina la ronda.','La arruina','No tanto'),
('mate-prestado','Mate','bardo','active','Devolver un mate prestado con yerba vieja es falta de respeto.','Lo es','Exageran'),
('cafe-pago','Mate','bardo','active','El que dice “yo invito el café” gana derecho a elegir el lugar.','Gana derecho','No decide'),
('plata-opina','Salidas','bardo','active','El que no pone plata pero opina del lugar pierde un voto.','Lo pierde','Lo conserva'),
('foto-irse','Salidas','bardo','active','Pedir foto grupal cuando todos se quieren ir es abuso de confianza.','Es abuso','Es tradición'),
('queda-bien','Salidas','bardo','active','Decirte “te queda bien” antes de salir no siempre es ayuda.','No siempre','Siempre ayuda'),
('salida-cerrar','Salidas','bardo','active','El que propone irse debería encargarse de cerrar la cuenta.','Debería','No tiene por qué'),
('cancion-cambiar','Música','bardo','active','Pedir cambiar una canción porque no la conocés es abusar de confianza.','Es abuso','Es válido'),
('musica-dj','Música','bardo','active','Decir “yo pongo música” sin que nadie lo pida es una advertencia.','Lo es','No tanto'),
('parlante-opinar','Música','bardo','active','Quien monopoliza el parlante pierde derecho a elegir el próximo tema.','Lo pierde','Lo conserva'),
('tema-cortado','Música','bardo','active','Cambiar un tema antes del estribillo debería requerir consenso.','Requiere','No hace falta'),
('desaparece-pide','Amistades','bardo','active','El que desaparece del grupo y vuelve sólo para pedir algo queda en falta.','Queda en falta','No tanto'),
('tres-dias','Amistades','bardo','active','Quien tarda tres días en responder no puede reclamar que no le avisaron.','No puede','Puede reclamar'),
('jajaj-rendirse','Amistades','bardo','active','Mandar “jajaj” después de discutir es rendirse sin admitirlo.','Es rendirse','Es bajar tensión'),
('silenciar-grupo','Amistades','bardo','active','Silenciar el grupo una semana y volver con preguntas es una provocación.','Lo es','Es válido'),
('fuego-chamuyo','Redes','bardo','active','Responder una historia sólo con fuego es chamuyo aunque lo niegues.','Es chamuyo','Depende'),
('jaja-mal','Redes','bardo','active','Responder “jaja mal” no alcanza para seguir una conversación.','No alcanza','Alcanza'),
('historias-todo','Redes','bardo','active','Subir toda la salida a historias es no vivirla del todo.','Es así','Nada que ver'),
('clavado-visto','Redes','bardo','active','Clavar visto después de proponer un plan es cancelar sin decirlo.','Es cancelar','No cuenta'),
('facultad-fotocopia','Facultad','bardo','active','Pedir apuntes cinco minutos antes del parcial es jugar con suerte.','Es jugar','Hay que ayudar'),
('apuntes-explicar','Facultad','bardo','active','Compartir apuntes no obliga a explicar todo después.','No obliga','Obliga'),
('trabajo-grupo','Facultad','bardo','active','El que no aparece en el trabajo grupal no puede corregir al final.','No puede','Puede opinar'),
('parcial-grupo','Facultad','bardo','active','Salir del parcial y comparar respuestas sólo aumenta el sufrimiento.','Lo aumenta','Ayuda'),
('trabajo-camara-bardo','Laburo','bardo','active','Tener la cámara apagada no autoriza a desaparecer de la reunión.','No autoriza','Puede pasar'),
('laburo-urgente','Laburo','bardo','active','Un mensaje que dice “urgente” después de horario debería tener multa.','Debería','Exageran'),
('laburo-responder','Laburo','bardo','active','Responder “lo veo” es una forma elegante de no hacerlo hoy.','Lo es','No necesariamente'),
('laburo-microfono','Laburo','bardo','active','Dejar el micrófono abierto con ruido de fondo es una falta de respeto.','Lo es','Pasa'),
('viaje-responsable','Viajes','bardo','active','En un viaje siempre aparece alguien que se cree responsable sin votación.','Siempre aparece','Hace falta'),
('viaje-cuentas','Viajes','bardo','active','Anotar cada gasto del viaje puede ordenar, pero también arruinar el clima.','Lo arruina','Lo salva'),
('pre-viaje-maleta','Viajes','bardo','active','Hacer la valija la noche anterior es vivir al límite.','Es vivir al límite','Es normal'),
('viaje-puntual','Viajes','bardo','active','Quien demora al grupo en una excursión debería invitar algo después.','Debería','No hace falta'),
('casa-ajena','Convivencia','bardo','active','Abrir la heladera ajena sin preguntar ya cruza una línea.','La cruza','Exageran'),
('convivencia-lista','Convivencia','bardo','active','La lista de compras compartida sólo sirve si alguien la persigue.','Sólo así','Igual sirve'),
('baño-ocupado','Convivencia','bardo','active','Tardar demasiado en el baño cuando hay gente esperando es egoísmo.','Es egoísmo','Depende'),
('orden-ajeno','Convivencia','bardo','active','Ordenar cosas ajenas sin preguntar genera más lío que ayuda.','Genera lío','Es ayudar'),
('paga-persigue','Plata','bardo','active','El que se ofrece a pagar y después persigue transferencias se contradice.','Se contradice','Es ordenado'),
('calculadora-salida','Plata','bardo','active','Dividir hasta el último peso puede ser ordenado, pero mata la salida.','La mata','Es justo'),
('amistad-prestamo','Plata','bardo','active','Prestar plata entre amigos necesita fecha, aunque dé fiaca.','Necesita fecha','No hace falta'),
('vuelto-chico','Plata','bardo','active','Cobrar un vuelto mínimo varios días después es demasiado.','Es demasiado','Se cobra'),
('juego-enojado','Juegos','bardo','active','Enojarse por perder arruina más que hacer trampa una vez.','Arruina más','No tanto'),
('juego-reglas-bardo','Juegos','bardo','active','Explicar las reglas mientras todos quieren jugar es querer mandar.','Es mandar','Es necesario'),
('truco-senias','Juegos','bardo','active','Negar una seña obvia en el truco es parte del juego.','Es parte','Es trampa'),
('revancha-eterna','Juegos','bardo','active','Pedir revancha hasta ganar convierte el juego en trámite.','Lo convierte','Es competir'),
('futbol-repeticion-bardo','Fútbol','bardo','active','Frenar la charla para ver una repetición es prioridad legítima.','Es prioridad','Es exagerado'),
('futbol-cabala','Fútbol','bardo','active','Cambiarse de lugar en un partido porque “da suerte” merece respeto.','Merece respeto','Es cualquiera'),
('futbol-grito','Fútbol','bardo','active','Gritar un gol antes de que entre es mufar al grupo.','Es mufar','No existe'),
('futbol-resultado','Fútbol','bardo','active','Spoilear el resultado de un partido grabado es imperdonable.','Lo es','No tanto'),
('cancelar-multa','Planes','bardo','active','Cancelar el mismo día debería tener multa social.','Debería','Exageran'),
('hagan-lo-que','Planes','bardo','active','Decir “hagan lo que quieran” te quita derecho a criticar el plan.','Te lo quita','Podés criticar'),
('extra-sin-avisar','Planes','bardo','active','Caer con alguien extra sin avisar cambia el plan para todos.','Lo cambia','No tanto'),
('planes-confirmar','Planes','bardo','active','Decir “después confirmo” hasta último momento ya es una respuesta.','Ya lo es','No cuenta'),
('ya-salgo','Hábitos','bardo','active','Decir “llego en cinco” desde la ducha ya cuenta como mentira.','Cuenta','No cuenta'),
('no-tomo','Hábitos','bardo','active','Decir “yo no tomo mucho” al empezar la noche debería quedar registrado.','Debería','Exageran'),
('habitos-alarma','Hábitos','bardo','active','Poner cinco alarmas no te hace más puntual.','No te hace','Sí ayuda'),
('super-hambre','Hábitos','bardo','active','Ir al súper con hambre te hace comprar cualquier cosa.','Te hace','Se controla'),
('asado-ensalada-bardo','Asado','bardo','reserve','Llegar al asado sin aportar nada y elegir el corte es demasiado.','Es demasiado','Puede elegir'),
('mate-critico','Mate','bardo','reserve','Criticar cómo ceban mate sin ofrecerte a cebar es caretear.','Es caretear','Es sinceridad'),
('salida-llegada','Salidas','bardo','reserve','Llegar tarde pero pedir mesa cerca de la puerta es tener cara.','Es tener cara','Es práctico'),
('musica-pedido','Música','bardo','reserve','Pedir el mismo tema dos veces en la noche debería tener límite.','Tiene límite','Se puede'),
('amistad-cumple','Amistades','bardo','reserve','Olvidarte un cumpleaños y aparecer con excusa empeora todo.','Empeora','Se arregla'),
('redes-etiqueta','Redes','bardo','reserve','Etiquetar a alguien en una foto fea requiere permiso tácito.','Requiere permiso','Da igual'),
('facultad-ausente','Facultad','bardo','reserve','Quien no fue nunca no puede pedir resumen personalizado.','No puede','Hay que pasarle'),
('laburo-llamada','Laburo','bardo','reserve','Llamar sin avisar por algo que entraba en un mensaje es invasivo.','Es invasivo','Es más rápido'),
('viaje-despertar','Viajes','bardo','reserve','Despertar a todos temprano en vacaciones es abuso de confianza.','Es abuso','Hay que aprovechar'),
('convi-luz','Convivencia','bardo','reserve','Dejar luces prendidas en una casa ajena no es un detalle.','No es detalle','Es mínimo'),
('plata-cobro','Plata','bardo','reserve','Recordar una deuda en el grupo expone de más.','Expone de más','Resuelve rápido'),
('juego-ganador','Juegos','bardo','reserve','El ganador que explica por qué ganó arruina la victoria.','La arruina','La celebra'),
('futbol-picada','Fútbol','bardo','reserve','Elegir la picada durante el partido distrae más de la cuenta.','Distrae','Es parte'),
('plan-dresscode','Planes','bardo','reserve','Poner dress code para una juntada casera es de más.','Es de más','Suma onda'),
('habito-respuesta','Hábitos','bardo','reserve','Responder “ahí voy” y no moverte por diez minutos es chamuyo.','Es chamuyo','Es normal'),
('asado-carbon','Asado','bardo','reserve','Llegar con carbón salva más que llegar con postre.','Salva más','Postre gana'),
('mate-galletitas','Mate','bardo','reserve','Poner galletitas en la ronda de mate mejora todo.','Mejora todo','Ensucia'),
('salida-ubicacion','Salidas','bardo','reserve','Mandar “estoy llegando” sin ubicación no informa nada.','No informa','Alcanza'),
('musica-vergüenza','Música','bardo','reserve','Una canción vergonzosa se canta más fuerte si todos la saben.','Más fuerte','Se evita'),
('amistad-planes','Amistades','bardo','reserve','El amigo que organiza todo gana derecho a quejarse un poco.','Gana derecho','No se queja')
on conflict (id) do update set category=excluded.category,intensity=excluded.intensity,status=excluded.status,text=excluded.text,side_a=excluded.side_a,side_b=excluded.side_b;
