+-- Contramano Bardo V3: catálogo editorial final, seguro para una base con V1/V2.
-- No borra prompts, salas, rondas, votos, eventos ni políticas.
-- Archiva sólo Bardo previo para conservar historial sin seleccionarlo en mazos nuevos.

update public.prompts
set status='archived', audience_type='neutral'
where intensity='bardo' and id not like 'bardo-v3-%';

insert into public.prompts(id,category,intensity,status,audience_type,text,side_a,side_b) values
('bardo-v3-pareja-ubicacion', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Tener ubicación compartida con tu pareja es una forma de control?', 'Sí, es control', 'No, es cuidado'),
('bardo-v3-pareja-ex-diario', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Hablar con tu ex todos los días significa que no cerraste la relación?', 'Sí, no cerraste', 'No, es amistad'),
('bardo-v3-pareja-fotos-sugerentes', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Subir fotos sugerentes estando en pareja busca atención de otras personas?', 'Sí, busca atención', 'No, comparte fotos'),
('bardo-v3-pareja-celular', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Revisar el celular de tu pareja está mal aunque encuentres algo?', 'Sí, está mal', 'No, se justifica'),
('bardo-v3-pareja-mejores-amigos', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Tener mejores amigos ocultos estando en pareja es sospechoso?', 'Sí, es sospechoso', 'No, es privado'),
('bardo-v3-pareja-fines-semana', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Salir todos los fines de semana sin tu pareja falta el respeto a la relación?', 'Sí, falta el respeto', 'No, está bien'),
('bardo-v3-pareja-ropa', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Criticar cómo se viste tu pareja es querer controlarla?', 'Sí, es control', 'No, es cuidar'),
('bardo-v3-pareja-beso-boliche', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Un beso en un boliche estando de novio cuenta como infidelidad?', 'Sí, cuenta', 'No, no cuenta'),
('bardo-v3-pareja-follows', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Seguir gente nueva estando en pareja es una falta de respeto?', 'Sí, lo es', 'No, no lo es'),
('bardo-v3-pareja-redes', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿No subir nunca a tu pareja a redes significa que la escondés?', 'Sí, la escondés', 'No, es privacidad'),
('bardo-v3-pareja-chats-ex', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Guardar chats con tu ex es dejar una puerta abierta?', 'Sí, la deja abierta', 'No, es normal'),
('bardo-v3-pareja-contrasenas', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Compartir todas las contraseñas demuestra confianza?', 'Sí, la demuestra', 'No, demuestra desconfianza'),
('bardo-v3-pareja-viaje-ex', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Irse de viaje con tu ex estando en pareja está mal?', 'Sí, está mal', 'No, se puede'),
('bardo-v3-pareja-mentira', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Mentir dónde estás para evitar una pelea sigue siendo mentir?', 'Sí, sigue siendo mentir', 'No, evita un problema'),
('bardo-v3-pareja-ultima-conexion', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Mirar la última conexión de tu pareja es buscar sufrir?', 'Sí, es buscar sufrir', 'No, da tranquilidad'),
('bardo-v3-pareja-historias', 'Pareja y celos', 'bardo', 'active', 'neutral', '¿Ocultar historias a tu pareja es peor que no subirlas?', 'Sí, es peor', 'No, es privado'),
('bardo-v3-pareja-app-citas', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Tener una app de citas instalada estando en pareja es engañar?', 'Sí, es engañar', 'No, no cuenta'),
('bardo-v3-pareja-borrar-redes', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Pedirle a tu pareja que borre a alguien de redes es control?', 'Sí, es control', 'No, es un límite'),
('bardo-v3-pareja-like-ex', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Dar likes a fotos de tu ex teniendo pareja busca generar algo?', 'Sí, busca algo', 'No, no significa nada'),
('bardo-v3-pareja-cancela-amigos', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Cancelar planes con amigos por una pelea de pareja está mal?', 'Sí, está mal', 'No, es entendible'),
('bardo-v3-pareja-celular-dado-vuelta', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Dormir con el celular dado vuelta genera desconfianza?', 'Sí, genera desconfianza', 'No, es costumbre'),
('bardo-v3-pareja-onda', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Seguir hablando con alguien con quien hubo onda estando en pareja está mal?', 'Sí, está mal', 'No, se puede'),
('bardo-v3-pareja-intensa', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Decir “sos intensa” durante una discusión sirve para evitar responder?', 'Sí, evita responder', 'No, pone un límite'),
('bardo-v3-pareja-volver-ex', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Volver con tu ex por tercera vez es elegir el mismo problema?', 'Sí, es lo mismo', 'No, puede cambiar'),
('bardo-v3-citas-no-propone', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Después de dos semanas hablando todos los días, no proponer verse muestra falta de interés?', 'Sí, falta interés', 'No, quiere ir despacio'),
('bardo-v3-citas-madrugada', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Responder sólo de madrugada muestra que te tiene de segunda opción?', 'Sí, sos segunda opción', 'No, tiene horarios'),
('bardo-v3-citas-like-viejo', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Dar like a una foto vieja es una forma de chamuyo?', 'Sí, es chamuyo', 'No, es curiosidad'),
('bardo-v3-citas-reaparece', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Volver con un “perdón, colgué” después de un mes merece respuesta?', 'Sí, merece respuesta', 'No, ya fue'),
('bardo-v3-citas-primera-cuenta', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Dividir la cuenta en una primera cita queda mal?', 'Sí, queda mal', 'No, es justo'),
('bardo-v3-citas-tarde', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Llegar media hora tarde a una cita arruina el plan?', 'Sí, lo arruina', 'No, se espera'),
('bardo-v3-citas-visto', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Dejar en visto para no rechazar es peor que decir que no?', 'Sí, es peor', 'No, evita herir'),
('bardo-v3-citas-casa', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Invitar a casa en la primera cita deja claro que no buscás algo serio?', 'Sí, lo deja claro', 'No, no necesariamente'),
('bardo-v3-citas-cancela', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Cancelar dos citas seguidas muestra que no hay interés?', 'Sí, no hay interés', 'No, se complicó'),
('bardo-v3-citas-varias-personas', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Hablar con varias personas a la vez mientras conocés a alguien está mal?', 'Sí, está mal', 'No, es normal'),
('bardo-v3-citas-paga-todo', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Pagar todo en una primera cita puede ser una forma de chamuyo?', 'Sí, puede ser', 'No, es un gesto'),
('bardo-v3-citas-instagram', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Pedir Instagram antes de hablar es elegir por apariencia?', 'Sí, es elegir por foto', 'No, es normal'),
('bardo-v3-citas-borracho', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Si te escribe borracho, lo hace porque está aburrido?', 'Sí, está aburrido', 'No, te extraña'),
('bardo-v3-citas-foto-actual', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Pedir una foto actual antes de verse es superficial?', 'Sí, es superficial', 'No, es lógico'),
('bardo-v3-citas-post-cita', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Dejar de responder después de una cita ya es una respuesta?', 'Sí, ya respondió', 'No, puede volver'),
('bardo-v3-citas-reaparece-celos', 'Chamuyo, citas y límites', 'bardo', 'active', 'neutral', '¿Reaparecer cuando te ve con otra persona muestra celos?', 'Sí, muestra celos', 'No, es casualidad'),
('bardo-v3-citas-quimica', 'Chamuyo, citas y límites', 'bardo', 'reserve', 'neutral', '¿Decir “no sentí química” es mejor que desaparecer?', 'Sí, es mejor', 'No, es frío'),
('bardo-v3-citas-fluimos-hombre', 'Chamuyo, citas y límites', 'bardo', 'reserve', 'dirigida_a_hombres', '¿Cuando un hombre dice “fluimos”, está evitando comprometerse?', 'Sí, lo evita', 'No, va tranquilo'),
('bardo-v3-citas-vemos-mujer', 'Chamuyo, citas y límites', 'bardo', 'reserve', 'dirigida_a_mujeres', '¿Cuando una mujer dice “vemos” hasta el mismo día, deja otras opciones abiertas?', 'Sí, las deja', 'No, todavía decide'),
('bardo-v3-citas-fueguitos-hombre', 'Chamuyo, citas y límites', 'bardo', 'reserve', 'dirigida_a_hombres', '¿Cuando un hombre responde historias con fueguitos, está chamuyando?', 'Sí, está chamuyando', 'No, es un emoji'),
('bardo-v3-citas-no-propone-mujer', 'Chamuyo, citas y límites', 'bardo', 'reserve', 'dirigida_a_mujeres', '¿Cuando una mujer acepta planes pero nunca propone uno, muestra poco interés?', 'Sí, muestra poco interés', 'No, es su forma'),
('bardo-v3-citas-paga-hombre', 'Chamuyo, citas y límites', 'bardo', 'reserve', 'dirigida_a_hombres', '¿Que él pague una salida significa que espera algo a cambio?', 'Sí, lo espera', 'No, es un gesto'),
('bardo-v3-citas-paga-mujer', 'Chamuyo, citas y límites', 'bardo', 'reserve', 'dirigida_a_mujeres', '¿Que ella acepte que pagues una salida la hace interesada?', 'Sí, la hace', 'No, no la hace'),
('bardo-v3-citas-cara', 'Chamuyo, citas y límites', 'bardo', 'reserve', 'neutral', '¿Tener una cita cara en el primer encuentro es querer impresionar?', 'Sí, quiere impresionar', 'No, es su plan'),
('bardo-v3-citas-ex', 'Chamuyo, citas y límites', 'bardo', 'reserve', 'neutral', '¿Seguir hablando con tu ex mientras conocés a alguien está mal?', 'Sí, está mal', 'No, no hay exclusividad'),
('bardo-v3-amigos-chaparse', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Chaparse a alguien que le gusta a tu amigo es traición?', 'Sí, es traición', 'No, nadie pertenece a nadie'),
('bardo-v3-amigos-ex', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Salir con la ex de un amigo está mal aunque hayan pasado años?', 'Sí, está mal', 'No, ya fue'),
('bardo-v3-amigos-secreto', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Contarle un secreto del grupo a tu pareja rompe un código?', 'Sí, lo rompe', 'No, es normal'),
('bardo-v3-amigos-engano', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Si sabés que engañan a tu amiga, deberías decírselo?', 'Sí, hay que decirlo', 'No, no te metas'),
('bardo-v3-amigos-defender', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Defender a un amigo aunque esté equivocado es ser falso?', 'Sí, es ser falso', 'No, es lealtad'),
('bardo-v3-amigos-desaparece', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Desaparecer por una pareja nueva merece cargada del grupo?', 'Sí, merece cargada', 'No, es normal'),
('bardo-v3-amigos-vuelve', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Volver al grupo después de meses te devuelve el mismo lugar?', 'Sí, lo devuelve', 'No, no lo devuelve'),
('bardo-v3-amigos-extra', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Llevar a alguien nuevo a una juntada sin avisar está mal?', 'Sí, está mal', 'No, no cambia nada'),
('bardo-v3-amigos-hablar-mal', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Hablar mal de un amigo con todos menos con él es cobardía?', 'Sí, es cobardía', 'No, es descargarse'),
('bardo-v3-amigos-pelea-pareja', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Si tu amigo se pelea con su pareja, tenés que tomar partido?', 'Sí, hay que tomar partido', 'No, no hay que hacerlo'),
('bardo-v3-amigos-favores', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Un amigo que sólo aparece para pedir favores sigue siendo amigo?', 'Sí, sigue siendo amigo', 'No, se aprovecha'),
('bardo-v3-amigos-cumple', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Olvidarte el cumpleaños de un amigo merece más que un sticker?', 'Sí, merece más', 'No, alcanza'),
('bardo-v3-amigos-deuda', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Cobrarle una deuda a un amigo delante del grupo está mal?', 'Sí, está mal', 'No, hay que cobrar'),
('bardo-v3-amigos-subgrupo', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Armar un grupo aparte para una salida deja gente afuera?', 'Sí, la deja afuera', 'No, organiza mejor'),
('bardo-v3-amigos-inseguridad', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Hacer chistes con una inseguridad de un amigo es humor?', 'Sí, es humor', 'No, es mala leche'),
('bardo-v3-amigos-ex-mejor-amigo', 'Amistades y códigos', 'bardo', 'active', 'neutral', '¿Si tu mejor amigo se hace amigo de tu ex, está cruzando un límite?', 'Sí, lo cruza', 'No, se puede'),
('bardo-v3-amigos-mudanza', 'Amistades y códigos', 'bardo', 'reserve', 'neutral', '¿No ayudar en una mudanza te quita derecho a pedir ayuda después?', 'Sí, te lo quita', 'No, no tiene relación'),
('bardo-v3-redes-historia-visto', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Subir una historia mientras dejás un mensaje en visto es ignorar a propósito?', 'Sí, es a propósito', 'No, no tiene relación'),
('bardo-v3-redes-indirectas', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Tirar indirectas por historias es no animarse a hablar de frente?', 'Sí, no se anima', 'No, se descarga'),
('bardo-v3-redes-capturas', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Mandar capturas de un chat al grupo está mal aunque tengas razón?', 'Sí, está mal', 'No, sirve de prueba'),
('bardo-v3-redes-cuenta-falsa', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Tener una cuenta falsa para mirar gente es una red flag?', 'Sí, es red flag', 'No, es curiosidad'),
('bardo-v3-redes-mejores-amigos', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Sacar a alguien de mejores amigos después de una pelea es un mensaje?', 'Sí, es un mensaje', 'No, no significa nada'),
('bardo-v3-redes-comentario', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Borrar un comentario genera más sospecha que dejarlo?', 'Sí, genera sospecha', 'No, evita lío'),
('bardo-v3-redes-likes', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Dar likes a todas las historias cuenta como hablar con alguien?', 'Sí, cuenta como hablar', 'No, no cuenta'),
('bardo-v3-redes-foto', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Subir una foto donde otro sale mal está mal?', 'Sí, está mal', 'No, es tu foto'),
('bardo-v3-redes-memes', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Mandar memes en medio de una pelea es esquivar el tema?', 'Sí, lo esquiva', 'No, baja tensión'),
('bardo-v3-redes-historia-mensajes', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Mirar quién vio tu historia antes de responder mensajes es jugar con alguien?', 'Sí, es jugar', 'No, es normal'),
('bardo-v3-redes-ultima-conexion', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Ocultar la última conexión hace que todos la miren más?', 'Sí, la miran más', 'No, da tranquilidad'),
('bardo-v3-redes-audio-privado', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Reenviar un audio privado para ganar una discusión es jugar sucio?', 'Sí, juega sucio', 'No, muestra pruebas'),
('bardo-v3-redes-indirecta-destino', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Subir una indirecta y negar que tiene destinatario es mentir?', 'Sí, es mentir', 'No, es descargarse'),
('bardo-v3-redes-historia-vistas', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'active', 'neutral', '¿Borrar una historia por pocas vistas muestra que esperabas reacción?', 'Sí, esperaba reacción', 'No, cambió de idea'),
('bardo-v3-redes-ex-perfil', 'WhatsApp, Instagram, privacidad y redes', 'bardo', 'reserve', 'neutral', '¿Mirar todos los días el perfil de la nueva pareja de tu ex muestra que no superaste?', 'Sí, no superaste', 'No, es curiosidad'),
('bardo-v3-gym-ropa-ajustada', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Ir al gym con ropa muy ajustada también busca que te miren?', 'Sí, busca miradas', 'No, es comodidad'),
('bardo-v3-gym-entrenamientos', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Subir cada entrenamiento busca mostrarse más que motivar?', 'Sí, busca mostrarse', 'No, busca motivar'),
('bardo-v3-gym-filmar', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Filmarse en el gym cuando hay gente atrás está mal?', 'Sí, está mal', 'No, no molesta'),
('bardo-v3-gym-consejos', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Dar consejos de gym sin que te los pidan es querer figurar?', 'Sí, quiere figurar', 'No, quiere ayudar'),
('bardo-v3-gym-remera', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Sacarse la remera para entrenar es para que te miren?', 'Sí, es para eso', 'No, es comodidad'),
('bardo-v3-gym-foto-serie', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Tardar más en una foto que en una serie muestra que vas por contenido?', 'Sí, vas por contenido', 'No, es descanso'),
('bardo-v3-gym-perfume', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Ir perfumado al gym también es ir a levantarse gente?', 'Sí, es para levantar', 'No, es higiene'),
('bardo-v3-gym-tecnica', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Corregir la técnica ajena sin permiso es agrandarse?', 'Sí, es agrandarse', 'No, es ayudar'),
('bardo-v3-gym-cambio-fisico', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Mostrar un cambio físico siempre busca aprobación?', 'Sí, busca aprobación', 'No, comparte progreso'),
('bardo-v3-gym-dos-maquinas', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Usar dos máquinas al mismo tiempo está mal?', 'Sí, está mal', 'No, ahorra tiempo'),
('bardo-v3-gym-levantar', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Vestirse para levantar en el gym está mal?', 'Sí, está mal', 'No, no tiene nada malo'),
('bardo-v3-gym-cuerpo', 'Gym, imagen, ropa y validación', 'bardo', 'active', 'neutral', '¿Comentar el cuerpo de alguien en el gym está mal aunque sea un elogio?', 'Sí, está mal', 'No, es un elogio'),
('bardo-v3-salidas-cuenta', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Pedir lo más caro y dividir igual es aprovecharse?', 'Sí, se aprovecha', 'No, es la cuenta'),
('bardo-v3-salidas-pone-mas', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿El que pone más plata debería decidir más?', 'Sí, debería decidir', 'No, se vota igual'),
('bardo-v3-salidas-deuda', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Cobrar una deuda chica delante de todos es humillar?', 'Sí, humilla', 'No, hay que cobrar'),
('bardo-v3-salidas-prestado', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Pedir prestado para salir y elegir el lugar caro está mal?', 'Sí, está mal', 'No, puede elegir'),
('bardo-v3-salidas-tarde-hielo', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿El que llega tarde a la previa debería poner para el hielo?', 'Sí, debería poner', 'No, no compensa'),
('bardo-v3-salidas-cancelar', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Cancelar el mismo día debería bajar prioridad para el próximo plan?', 'Sí, debería bajar', 'No, es demasiado'),
('bardo-v3-salidas-extra', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Caer con gente extra sin avisar arruina el plan?', 'Sí, lo arruina', 'No, no cambia nada'),
('bardo-v3-salidas-temprano', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Irse temprano del boliche es no bancarse la salida?', 'Sí, no se la banca', 'No, sabe irse'),
('bardo-v3-salidas-propina', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Discutir la propina por monedas arruina la salida?', 'Sí, la arruina', 'No, es su plata'),
('bardo-v3-salidas-bar-caro', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Elegir un bar caro sabiendo que alguien no llega es mala leche?', 'Sí, es mala leche', 'No, cada uno decide'),
('bardo-v3-salidas-casa', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿El que nunca pone casa puede quejarse del lugar?', 'Sí, puede quejarse', 'No, no puede'),
('bardo-v3-salidas-ronda', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Pedir otra ronda cuando ya llegó la cuenta es querer que otro pague?', 'Sí, quiere eso', 'No, quiere seguir'),
('bardo-v3-salidas-vuelto', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Quedarse con el vuelto de una compra grupal es hacerse el vivo?', 'Sí, se hace el vivo', 'No, compensa gastos'),
('bardo-v3-vida-tp', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿El que no hizo nada en un trabajo grupal merece figurar?', 'Sí, merece figurar', 'No, no merece'),
('bardo-v3-vida-ia', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿Usar IA para hacer todo un trabajo cuenta como hacer el trabajo?', 'Sí, cuenta', 'No, no cuenta'),
('bardo-v3-vida-urgente', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿Mandar algo a las once de la noche vuelve urgente al resto?', 'Sí, es urgente', 'No, puede esperar'),
('bardo-v3-vida-apuntes', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿Pedir apuntes el día antes del parcial es aprovecharse?', 'Sí, se aprovecha', 'No, el grupo ayuda'),
('bardo-v3-vida-cocina', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿El que cocina debería quedar libre de lavar platos?', 'Sí, debería quedar libre', 'No, lava igual'),
('bardo-v3-vida-platos', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿Dejar platos en remojo cuenta como lavarlos?', 'Sí, cuenta', 'No, no cuenta'),
('bardo-v3-vida-home-office', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿Hacer home office permite desaparecer todo el día?', 'Sí, lo permite', 'No, hay que responder'),
('bardo-v3-vida-corregir', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿El que no apareció en el trabajo grupal puede corregir al final?', 'Sí, puede corregir', 'No, no puede'),
('bardo-v3-vida-itinerario', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿Armar un viaje minuto a minuto arruina el viaje?', 'Sí, lo arruina', 'No, evita caos'),
('bardo-v3-vida-excursion', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿Llegar tarde a una excursión debería costarte algo?', 'Sí, debería costar', 'No, no corresponde'),
('bardo-v3-vida-vacaciones', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿Despertar temprano a todos en vacaciones está mal?', 'Sí, está mal', 'No, hay que aprovechar'),
('bardo-v3-vida-renunciar', 'Convivencia, facultad, trabajo, viajes y vida adulta', 'bardo', 'active', 'neutral', '¿Renunciar sin tener otro trabajo es irresponsable?', 'Sí, es irresponsable', 'No, hay que animarse'),
('bardo-v3-pareja-novia-salir-hombre', 'Pareja y celos', 'bardo', 'reserve', 'dirigida_a_hombres', '¿Cuando un hombre exige que su novia no salga, está siendo controlador?', 'Sí, es controlador', 'No, pone un límite'),
('bardo-v3-pareja-exclusividad-ex-mujer', 'Pareja y celos', 'bardo', 'reserve', 'dirigida_a_mujeres', '¿Cuando una mujer pide exclusividad pero sigue hablando con el ex, está pidiendo ventajas?', 'Sí, pide ventajas', 'No, no tiene relación'),
('bardo-v3-pareja-exes-hombre', 'Pareja y celos', 'bardo', 'reserve', 'dirigida_a_hombres', '¿Cuando un hombre dice que todas sus ex están locas, suele ocultar su parte?', 'Sí, la oculta', 'No, tuvo mala suerte'),
('bardo-v3-pareja-vuelve-celos-mujer', 'Pareja y celos', 'bardo', 'reserve', 'dirigida_a_mujeres', '¿Cuando una mujer vuelve justo al verte con otra, vuelve por celos?', 'Sí, vuelve por celos', 'No, se dio cuenta'),
('bardo-v3-pareja-ropa-hombre', 'Pareja y celos', 'bardo', 'reserve', 'dirigida_a_hombres', '¿Cuando un hombre se enoja por la ropa de su pareja, busca controlarla?', 'Sí, busca controlarla', 'No, cuida la relación'),
('bardo-v3-pareja-instagram-ex-mujer', 'Pareja y celos', 'bardo', 'reserve', 'dirigida_a_mujeres', '¿Cuando una mujer revisa todo el Instagram de su ex, demuestra que no lo superó?', 'Sí, no lo superó', 'No, es curiosidad'),
('bardo-v3-pareja-hablar-otra-persona', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Pedirle a tu pareja que deje de hablar con alguien es controlar?', 'Sí, es controlar', 'No, es marcar un límite'),
('bardo-v3-salidas-sin-pareja', 'Salidas, previa, boliche y plata', 'bardo', 'active', 'neutral', '¿Una salida de amigos sin pareja debería poder hacerse sin drama?', 'Sí, debería poder', 'No, trae problemas'),
('bardo-v3-amigos-ocultan-grupo', 'Amistades y códigos', 'bardo', 'reserve', 'neutral', '¿Si te ocultan del grupo de amigos, significa que no te toman en serio?', 'Sí, no te toman en serio', 'No, no significa eso'),
('bardo-v3-amigos-yo-soy-asi', 'Amistades y códigos', 'bardo', 'reserve', 'neutral', '¿Decir “yo soy así” después de lastimar a alguien es evitar cambiar?', 'Sí, evita cambiar', 'No, es sinceridad'),
('bardo-v3-pareja-coquetea-instagram', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Si tu pareja coquetea por Instagram, está engañando?', 'Sí, está engañando', 'No, no cuenta'),
('bardo-v3-pareja-plan-b', 'Pareja y celos', 'bardo', 'reserve', 'neutral', '¿Tener un “plan B” mientras estás en pareja es infidelidad?', 'Sí, es infidelidad', 'No, es previsión')
on conflict (id) do update set
  category=excluded.category,
  intensity=excluded.intensity,
  status=excluded.status,
  audience_type=excluded.audience_type,
  text=excluded.text,
  side_a=excluded.side_a,
  side_b=excluded.side_b
where public.prompts.id like 'bardo-v3-%';
